version: '3'
services:
  db:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_user: postgres
      POSTGRES_PASSWORD: pass0000
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: development
    depends_on:
      - db
    volumes:
      - .:/taskleaf
    ports:
      - "3333:3000"
